### ISSUE TITLE
Search result pagination beyond limits

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo-rdm#217]
The UI seems to allow pagination beyond the 10k results threshold:

![Screenshot 2023-03-08 at 13 43 31](https://user-images.githubusercontent.com/1698163/223716316-d4f3843d-e1fe-422d-be66-b492dc4908ad.png)

and when you press that last page:

![Screenshot 2023-03-08 at 13 43 56](https://user-images.githubusercontent.com/1698163/223716400-51542938-289e-4862-af59-a043b4886b87.png)

### Expected

I would expect no more than a 999 pages to be visible with a 10k result set limit.

**Comment by kpsherva** [comment]
The issue was solved in invenio-app-ils by limiting the number of pages to maximum 10k results - since it is unlikely anyone will ever paginate that far - can be rediscussed if it is UX friendly enough

**Comment by lnielsen** [comment]
Just seeing how this was closed now. The problem with hardcoding 10k in the frontend, is that it can be changed on the backend. The value should be injected from the backend instead.

**Comment by martenson** [comment]
> since it is unlikely anyone will ever paginate that far 

This is a fairly bold call, especially since this does not seem to be documented at https://developers.zenodo.org/#representation35 and instead of e.g. returning an empty list it actually throws an error.

How should the implementers of this API treat this? Hard code the magic number of 10k and do not paginate more or perhaps catch the whole category of errors if `the page * page_size > 10k`?
