### ISSUE TITLE
Data migration: Record version relationships

### ISSUE THREAD

**Issue by kpsherva** [zenodo/zenodo-rdm#241]
`RDMVErsionState` is already being migrated however we are missing the drafts

**Comment by ppanero** [comment]
**PIDs**

There are 4 tables related to pids:
- pidstore_pid
- pidstore_recid
- pidstore_redirect
- pidrelations_pidrelation

The first one (`pidstore_pid`) is being migrated as part of the `records` stream. The
stream is creating the records `recid`, `doi` and `oai`, and the parents' `recid`
(equivalent to the concept recid). Missing:
- Parent `doi` (i.e. concept DOI)

`pidstore_recid` is a simple counter for the recid value, since that has changed in RDM
it does not need to be migrated. `pidrelations_pidrelation` is removed from RDM,
relationships are handled via de `rdm_versions_state` table. This last one is migrated
by the `records` stream. Missing:
- `next_draft`, deposits (i.e. drafts)

The complete `pidstore_redirect` is missing migration. Migration should be a 1-to-1?

**Records**

There are several tables related to records:

- records_metadata
- records_metadata_version
- transactions
- All the tables related to invenio-sipstore

`records_metadata` the extract query in ZenodoRDM only includes active children pids.
Parent records are migrated from the `conceptrecid` inside the metadata. Missing:
- Deposits/Drafts
- Deleted records

`records_metadata_version`, a decission is needed here. Do we want to migrate as is, and
then only transform if we need to recover? or potentially even migrate the versions
asynchronously (not during the main migration downtime).

`transactions` is not being migrated, is needed for auditing and produced by sql
continuum. Do we want to migrate it, and keep it? (not used atm in RDM).

`records_buckets` will be left as part of the files migration.

A decission is needed to integrate invenio-sipstore and the migrate the content of
its tables. If needed.

**Comment by ppanero** [comment]
drafts are good to go, they have 2 things missing:
- files (actual files, and bucket creation if they are new)
- we need a record cache to:
     - reuse the uuid of the record if the draft is of an existing record
     - to avoid yielding a PersistentIdentifier row if it already exists
